name: GitHub Actions Build and Deploy
on:
  push:
    branches:
      - master
jobs:
  git-mirror:
    runs-on: ubuntu-latest
    steps:
        - uses: actions/checkout@v1
        - uses: spyoungtech/mirror-action@master
          with:
            REMOTE: 'https://gitee.com/nfsqhia/github-nlp-progress.git'
            GIT_USERNAME: spyoungtech
            GIT_SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v1
    - name: Build and Deploy
      uses: JamesIves/github-pages-deploy-action@releases/v2
      env:
        ACCESS_TOKEN: ${{ secrets.deploy }}
        BRANCH: gh-pages
        FOLDER: build
        BUILD_SCRIPT: npm install --registry=https://registry.npm.taobao.org && npm run build
