name: GitHub Actions Build and Deploy
on:
  push:
    branches:
      - master
jobs:
  git-mirror:
    runs-on: ubuntu-latest
    steps:
      - name: Single repo mirror
        uses: xuMINGzhi9/github-nlp-progress@master
        with:
          src: github/xuMINGzhi9
          dst: gitee/nfsqhia
          dst_key: ${{ secrets.SSH_PRIVATE_KEY }}
          dst_token: ${{ secrets.GITEE_TOKEN }}
          white_list: "github-nlp-progress"
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v1
    - name: Build and Deploy
      uses: JamesIves/github-pages-deploy-action@releases/v2
      env:
        ACCESS_TOKEN: ${{ secrets.deploy }}
        BRANCH: gh-pages
        FOLDER: build
        BUILD_SCRIPT: npm install --registry=https://registry.npm.taobao.org && npm run build
